### ISSUE TITLE
Laravel 5 ServiceProvider

### ISSUE THREAD

**Issue by mackhankins** [diego1araujo/titleasy#1]
In order to work for L5, I had to change the ServiceProvider since package has been removed.  You might want to branch so a PR can be submitted. 

``` php
    public function boot()
    {
        //$this->package('diego1araujo/titleasy');
    }
```

**Comment by mackhankins** [comment]
Are you not supporting this anymore?

**Comment by diego1araujo** [comment]
check [1.0 branch](https://github.com/diego1araujo/titleasy/tree/1.0)
